name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - develop

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: osscar-org/jupyterlab-cube
          service-name: gh
          target-state: develop
          use-default-build-servers: true
          debug: true
